Fix error building with cuda when bazel server dies.
Prior to this commit, configure would export TF_NEED_CUDA to the
environment if being configured with CUDA support. This is picked up in
cuda_configure.bzl to set up the environment, specifically bits placed
under:

    $bazel_build_dir/external/local_config_cuda/crosstool

If the bazel server dies for any reason (eg. rebooting the machine), then
the cached workspace is loaded again and if `TF_NEED_CUDA` isn't found,
then the `crosstool` directory is wiped out and replaced with a dummy
directory. This leads to build errors like:

    ERROR: Building with --config=cuda but TensorFlow is not configured to
    build with GPU support. Please re-run ./configure and enter 'Y' at the
    prompt to build with GPU support.

Clearly configuring again and rebuilding from scratch isn't reasonable so
this commit makes `TF_NEED_CUDA` work like `TF_NEED_HDFS` and
`TF_NEED_GCP`, where the needed variables are written by `configure` into
config files.

The environment variable approach is left working as that is used by
Dockerfile.gpu and possibly some other users.

Fixes #4705.